// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var licenseNumber;

if (licenseNumber !== undefined) {
  console.log(licenseNumber.toString());
} else {
  console.log("no car");
}

var personHasACar = false;

exports.personHasACar = personHasACar;
exports.licenseNumber = licenseNumber;
/*  Not a pure module */
